
const Food =[
    {name:'arroz_blanco',
    calorias:110,
    carbohidratos:60,
    proteina:30,
    grasas:5,
    categoria:'prote'
    },
    {name:'pechuga_pollo',
    calorias:110,
    carbohidratos:60,
    proteina:30,
    grasas:5,
    categoria:'carbo'
    },
    {name:'Salmon',
    calorias:110,
    carbohidratos:60,
    proteina:30,
    grasas:5,
    categoria:'grasa'
    },
    {name:'patata',
    calorias:110,
    carbohidratos:60,
    proteina:30,
    grasas:5
    },
    {name:'Aguacate',
    calorias:110,
    carbohidratos:60,
    proteina:30,
    grasas:5
    },
    {name:'pasta',
    calorias:110,
    carbohidratos:60,
    proteina:30,
    grasas:5
    },
    {name:'ternera',
    calorias:110,
    carbohidratos:60,
    proteina:30,
    grasas:5
    },
    {name:'atun',
    calorias:110,
    carbohidratos:60,
    proteina:30,
    grasas:5
    },
    {name:'aceitunas',
    calorias:110,
    carbohidratos:60,
    proteina:30,
    grasas:5
    },
]
export default Food
